hydra: 
  run:
    dir: ./simulation_studies/composite_loss_simulation/outputs
  sweep:
    dir: ./simulation_studies/composite_loss_simulation/outputs
    subdir: ${loss_BC_weight} weight_${hidden_layers}_${optimizer}_${optimizer_threshold}_${poisson_equation}
  sweeper:
    params:
      +embeddings_per_dim: 2
      +hidden_layers: "[20, 20, 20, 20], [64, 64, 64, 64, 64, 64]"
      +poisson_equation: "eigenfunc, const_source, non_const_BC"
      +batch_size: 128
      +epochs: 15000
      +optimizer: "Adam"
      +has_embedding_layer: False
      +optimizer_threshold: 3000, 7000, 12000
      +loss_BC_weight: 2, 10, 15, 20, 30, 50
  job:
    chdir: True

  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 12  # Run 6 jobs in parallel

defaults:
  - override hydra/launcher: joblib

model:
  type: "v0"
