#!/bin/bash -l
#SBATCH --gres=gpu:1
#SBATCH --qos=normal
#SBATCH --account=master
#SBATCH --time=8:00:00

module purge
module load gcc cuda

# Run Hydra with multirun
# python simulation_studies/weakly_enforcing_BC/weakly_enforcing_BC.py -m
# python simulation_studies/weakly_enforcing_BC/weakly_enforcing_BC.py -m
# python simulation_studies/benchmark/benchmark.py -m
# nvprof python simulation_studies/weakly_enforcing_BC/weakly_enforcing_BC.py
# nvidia-smi
# python -c "import torch; print(torch.cuda.is_available()), print(torch.version.cuda)"
python simulation_studies/harmonic_maps/harmonic_maps_train.py -m
# python simulation_studies/model_v1_simulation/model_v1_simulation.py -m
# python experiments/parametric_hm/main.py