defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: ./simulation_studies/weakly_enforcing_BC/outputs
  sweep:
    dir: ./simulation_studies/weakly_enforcing_BC/outputs
    subdir: ${boundary_batch_ratio}_${poisson_equation}_${activation_function}
  sweeper:
    params:
      +hidden_layers: "[64, 64, 64, 64, 64, 64]"
      +poisson_equation: "non_const_BC"
      +batch_size: 128
      +epochs: 8000
      +optimizer: "Adam"
      +optimizer_threshold: 7000
      +loss_BC_weight: 30
      +seed: 0
      #+boundary_batch_ratio: 0.25, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0, 128.0
      #+activation_function: "tanh, sigmoid, gelu"
      +boundary_batch_ratio: 0.25
      +activation_function: "tanh"
  job:
    chdir: True

  launcher:
    # submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 120
    cpus_per_task: null
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: null
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: null
    qos: "normal"
    comment: null
    constraint: null
    exclude: null
    gres: gpu:1
    cpus_per_gpu: 1
    gpus_per_task: 1
    mem_per_gpu: null
    mem_per_cpu: null
    account: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    setup: null

model:
  type: "v2"

# defaults:
#   - override hydra/launcher: submitit_slurm

# hydra:
#   run:
#     dir: ./simulation_studies/weakly_enforcing_BC/outputs
#   job:
#     chdir: True
#   launcher:
#     _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# model:
#   type: "v2"

# # Model training parameters (for single run)
# hidden_layers: [64, 64, 64, 64, 64, 64]
# poisson_equation: "non_const_BC"
# batch_size: 128
# epochs: 15000
# optimizer: "Adam"
# optimizer_threshold: 7000
# loss_BC_weight: 30
# seed: 0
# boundary_batch_ratio: 0.25
# activation_function: "tanh"
