hydra:
  run:
    dir: ./simulation_studies/model_v0_simulation/outputs
  sweep:
    dir: ./simulation_studies/model_v0_simulation/outputs
    subdir: ${numb_batches} batches_${embeddings_per_dim} embeddings_per_dim
  sweeper:
    params:
      +numb_batches: 100
      +embeddings_per_dim: 0  # This will not be used
      +embedding_layer: False
      +hidden_layers: [128, 256, 128]
      +poisson_equation: "diff"
  job:
    chdir: True

model:
  type: "v0"
  
  optimizer: "adam"