defaults:
  - _self_
  - override hydra/launcher: submitit_slurm
  

hydra:
  run:
    dir: ./simulation_studies/harmonic_maps/outputs
  sweep:
    dir: ./simulation_studies/harmonic_maps/outputs
    subdir: ${PDE.name}_f_x_${PDE.PDE_kwargs.frequency_x}_f_y_${PDE.PDE_kwargs.frequency_y}_second_lr_1e-5
  sweeper:
    params:
      PDE.PDE_kwargs.frequency_x: -1.5
      PDE.PDE_kwargs.frequency_y: 3.0


  job:
    chdir: True

  launcher:
    # submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 2880
    cpus_per_task: null
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: null
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: null
    qos: "normal"
    comment: null
    constraint: null
    exclude: null
    gres: gpu:1
    cpus_per_gpu: 1
    gpus_per_task: 1
    mem_per_gpu: null
    mem_per_cpu: null
    account: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    setup: null


PDE:
  name: "sin_boundaries_hm"
  PDE_kwargs:
    curvature: 0.5
    frequency_x: 1
    frequency_y: 1

model:
  type: "v2"
  model_kwargs:
    nodes_hidden_layers: [64, 64, 64, 64, 64, 64]
    activation_function: "gelu"
    has_embedding_layer: False
    output_dim: 2

train:
  batch_size: 128 
  n_epochs: 15000 
  optimizer: "Adam"
  optimizer_threshold: 7000
  loss_BC_weight: 20
  save_BC_loss: True
  boundary_batch_ratio: 1
  seed: 42
  interior_sampler: null
  boundary_sampler: null

solver:
  nx: 21
  ny: null
  p: 3